import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import Database from 'better-sqlite3'
import Ajv2020 from 'ajv/dist/2020'
import { readFileSync } from 'node:fs'
import { ConsumptionStore } from '../consumption/store'
import { LocalOwnerVerifier } from './verifier'
import { FIXED_ACTION, OBSERVATION_DIGEST_VALUE } from './contracts'
import { PROFILE_ID, PROFILE_VERSION, digestEnvelope, recordDigest } from './jcs'

const TOKEN='synthetic-fixture-credential-0001'
const PIN='18dedc4a2ef445e142ef395c62883d3448ad0ee021dbde789fe6b14e94538c34'
const base=(decisionId='d1',packet='packet-1')=>({hacp_version:'v0.1-draft',record_kind:'hacp.human_decision_gate',decision_id:`human-${decisionId}`,packet_id:packet,profile_id:'hacp-base-draft',profile_version:'v0.1-draft',decision_matrix_version:'0.1',from_status:'approved',to_status:'in_progress',decision:'start_work',reason:'fixture human start act',created_at:'2026-09-05T00:00:00.000Z',actor_id:'fixture-human',actor_kind:'human',actor_verification_source:'signed_human_attestation',authentication_context:{interaction_channel:'cli',auth_event_ref:`event-${decisionId}`,secret_material_present:false},forbidden_effects_confirmed:[],evidence:[`candidate-decision:${decisionId}`,`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]})
function setup(issuer='fixture-issuer',clock?:()=>{wallTime:string,monotonicNanoseconds:string}){const dir=mkdtempSync(path.join(tmpdir(),'lo-'));const dbPath=path.join(dir,'store.db');const config={dbPath,issuerId:issuer,actorId:'fixture-human',credential:TOKEN,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'active',pin:PIN},test:clock?{clock}:undefined};return{dir,dbPath,config,v:new LocalOwnerVerifier(config)}}
function decision(id='d1'){const b=base(id);return{decisionId:id,humanEventRef:b.decision_id,baseDecisionRef:b.packet_id,baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,b),requestRef:'request-1',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z',baseDecision:b}}
function claim(d:any,id='c1'){return{decisionId:d.decisionId,decisionDigest:d.digest,claimId:id,attemptKey:'attempt-1',successorId:'successor-1',requestRef:'request-1',action:FIXED_ACTION,claimedAt:'2026-09-05T00:00:01.000Z',expiresAt:'2099-01-01T00:00:00.000Z'}}
function admitted(s=setup()){const d=s.v.recordDecision(TOKEN,decision());assert(d.ok);const c=s.v.admitClaim(TOKEN,claim(d.value));assert(c.ok);return{s,d:d.value,c:c.value}}

test('JCS known vectors and profile selection',()=>{assert.equal(recordDigest('decision',{recordKind:'decision',profileId:PROFILE_ID,profileVersion:PROFILE_VERSION,issuerId:'issuer-example',decisionId:'decision-example-001'}).value,'9de745ae777609863f309450a0455da5ad7a1d166f8f29734d8a2d35d569f014');assert.equal(digestEnvelope(`${PROFILE_ID}.observation.0.1-candidate`,{operationId:'observe_fixed_payload',payload:'HACP_LOCAL_OWNER_CONTINUATION_PROBE_V1'}).value,OBSERVATION_DIGEST_VALUE);assert.throws(()=>new LocalOwnerVerifier({...setup().config,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'revoked',pin:PIN}}))})
test('authentication precedes disclosure and human act/base companion binding',()=>{const s=setup();try{assert.deepEqual(s.v.inspect('wrong','missing'),{ok:false,stop:'MISSING_AUTHORITY',detail:'access denied'});for(const mutate of [(x:any)=>{x.baseDecision.decision='approve_next_packet'},(x:any)=>{x.baseDecision.evidence=[]},(x:any)=>{x.baseDecisionDigest.value='0'.repeat(64)},(x:any)=>{x.issuerId='forged'}]){const x:any=structuredClone(decision());mutate(x);const r=s.v.recordDecision(TOKEN,x);assert.equal(r.ok,false)}assert.equal(s.v.inspect(TOKEN,'d1').ok,false)}finally{s.v.close();rmSync(s.dir,{recursive:true})}})
test('fixed action, expiry and exact claim replay bindings',()=>{const s=setup();try{const bad:any=decision();bad.action={...FIXED_ACTION,parameters:{payload:'evil'}};assert.equal((s.v.recordDecision(TOKEN,bad) as any).stop,'SCOPE_CONFLICT');const d=s.v.recordDecision(TOKEN,decision());assert(d.ok);const ci=claim(d.value);const c=s.v.admitClaim(TOKEN,ci);assert(c.ok);assert.equal((s.v.admitClaim(TOKEN,ci) as any).value.digest.value,(c.value.digest as any).value);for(const key of ['successorId','attemptKey','requestRef'] as const){const changed={...ci,[key]:'changed'};assert.equal((s.v.admitClaim(TOKEN,changed) as any).stop,'SCOPE_CONFLICT')}assert.equal((s.v.admitClaim(TOKEN,{...ci,claimId:'c2'}) as any).stop,'SCOPE_CONFLICT')}finally{s.v.close();rmSync(s.dir,{recursive:true})}})
test('issuer namespace is separate while legacy decision id blocks without rewrite',()=>{const s=setup('issuer-a');try{new ConsumptionStore(s.dbPath).claim({decisionId:'legacy',chosenOption:'x',rationale:'x',decidedAt:'2026-09-05T00:00:00.000Z',decisionRequestId:'r',permittedAction:'x'},'old');const db=new Database(s.dbPath);const bytes=(db.prepare('select receipt_json from consumption_receipts where decision_id=?').get('legacy') as any).receipt_json;db.close();assert.equal((s.v.recordDecision(TOKEN,decision('legacy')) as any).stop,'MISSING_AUTHORITY');const db2=new Database(s.dbPath);assert.equal((db2.prepare('select receipt_json from consumption_receipts where decision_id=?').get('legacy') as any).receipt_json,bytes);db2.close();const other=new LocalOwnerVerifier({...s.config,issuerId:'issuer-b'});assert(other.recordDecision(TOKEN,decision()).ok);other.close()}finally{s.v.close();rmSync(s.dir,{recursive:true})}})
test('happy guarded start persists intent/result and never reexecutes',()=>{const a=admitted();try{const input={decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION};const r=a.s.v.guardedStart(TOKEN,input);assert(r.ok);assert.deepEqual(r.value.observation,{operationId:'observe_fixed_payload',payload:'HACP_LOCAL_OWNER_CONTINUATION_PROBE_V1'});assert.equal(r.value.result.observationDigest.value,OBSERVATION_DIGEST_VALUE);assert.equal(r.value.intent.admittedAt,r.value.intent.clockSample.wallTime);assert.equal(r.value.result.observedAt,r.value.result.observationClockSample.wallTime);assert.equal((a.s.v.guardedStart(TOKEN,input) as any).stop,'HUMAN_DECISION_REQUIRED')}finally{a.s.v.close();rmSync(a.s.dir,{recursive:true})}})
test('restart after claim and status revocation fail closed',()=>{const a=admitted();a.s.v.close();const reopened=new LocalOwnerVerifier(a.s.config);try{assert.equal((reopened.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION}) as any).stop,'HUMAN_DECISION_REQUIRED')}finally{reopened.close();rmSync(a.s.dir,{recursive:true})};const b=admitted();try{assert(b.s.v.revoke(TOKEN,'d1','claim').ok);assert.equal((b.s.v.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION}) as any).stop,'STALE_PACKET');assert.equal((b.s.v.revoke(TOKEN,'d1','claim') as any).stop,'STALE_PACKET')}finally{b.s.v.close();rmSync(b.s.dir,{recursive:true})}})
test('status corruption and missing durable readback deny observation',()=>{for(const sql of ["delete from local_owner_records where kind='claim'","update local_owner_slots set claim_status_head='bad'","update local_owner_status set sequence=4 where target_kind='claim'"]){const a=admitted();try{new Database(a.s.dbPath).exec(sql);const r=a.s.v.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION});assert.equal(r.ok,false);assert(['UNVERIFIED_ASSUMPTION','MISSING_AUTHORITY'].includes((r as any).stop))}finally{a.s.v.close();rmSync(a.s.dir,{recursive:true})}}})
test('clock rollback, expiry at handoff and uncertain observation retain intent',()=>{for(const samples of [[{wallTime:'2026-09-05T00:00:02.000Z',monotonicNanoseconds:'2'},{wallTime:'2026-09-05T00:00:01.000Z',monotonicNanoseconds:'1'}],[{wallTime:'2098-01-01T00:00:00.000Z',monotonicNanoseconds:'1'},{wallTime:'2100-01-01T00:00:00.000Z',monotonicNanoseconds:'2'}]]){let i=0;const a=admitted(setup('fixture-issuer',()=>samples[Math.min(i++,1)]));try{const r=a.s.v.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION});assert.equal(r.ok,false);assert.equal((a.s.v.inspect(TOKEN,'d1') as any).value.start_intent_digest!==null,true)}finally{a.s.v.close();rmSync(a.s.dir,{recursive:true})}}})

test('all five closed candidate record schemas validate emitted records',()=>{const a=admitted();try{const start=a.s.v.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION});assert(start.ok);const db=new Database(a.s.dbPath,{readonly:true});const rows=db.prepare('select kind,record_json from local_owner_records').all() as any[];const statuses=db.prepare('select record_json from local_owner_status').all() as any[];db.close();const ajv=new Ajv2020({strict:false});for(const kind of ['decision','claim','status-event','start-intent','start-result']){const schema=JSON.parse(readFileSync(path.resolve(`schemas/local-owner/${kind}.schema.json`),'utf8'));const validate=ajv.compile(schema);const records=kind==='status-event'?statuses.map(x=>JSON.parse(x.record_json)):rows.filter(x=>x.kind===kind).map(x=>JSON.parse(x.record_json));assert(records.length>0,kind);for(const record of records)assert(validate(record),`${kind}: ${ajv.errorsText(validate.errors)}`)}}finally{a.s.v.close();rmSync(a.s.dir,{recursive:true})}})
test('closed clock shape and unknown clock fail before observation',()=>{for(const sample of [{wallTime:'2026-09-05T00:00:02.000Z',monotonicNanoseconds:'01'},{wallTime:'2026-09-05T00:00:02.000Z',monotonicNanoseconds:'1',extra:true},null]){const s=setup('fixture-issuer',()=>{if(sample===null)throw Error('clock unavailable');return sample as any});const a=admitted(s);try{const r=a.s.v.guardedStart(TOKEN,{decisionId:'d1',claimId:'c1',intentId:'i1',successorId:'successor-1',action:FIXED_ACTION});assert.equal((r as any).stop,'UNVERIFIED_ASSUMPTION')}finally{a.s.v.close();rmSync(a.s.dir,{recursive:true})}}})
