import assert from 'node:assert/strict'
import { fork, execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { LocalOwnerVerifier, APPROVED_PROFILE_PIN } from '../src/local-owner/verifier'
import { FIXED_ACTION } from '../src/local-owner/contracts'
import { PROFILE_ID, PROFILE_VERSION, digestEnvelope, recordDigest } from '../src/local-owner/jcs'

const out=path.resolve(process.argv[2]??'');assert(process.argv[2],'output required');mkdirSync(path.dirname(out),{recursive:true});mkdirSync(out)
const token='synthetic-proof-credential-000000';const dbPath=path.join(out,'proof.db');let mono=0
const base={hacp_version:'v0.1-draft',record_kind:'hacp.human_decision_gate',decision_id:'human-proof',packet_id:'packet-proof',profile_id:'hacp-base-draft',profile_version:'v0.1-draft',decision_matrix_version:'0.1',from_status:'approved',to_status:'in_progress',decision:'start_work',reason:'synthetic proof act',created_at:'2026-09-05T00:00:00.000Z',actor_id:'synthetic-human',actor_kind:'human',actor_verification_source:'signed_human_attestation',authentication_context:{interaction_channel:'cli',auth_event_ref:'synthetic-event',secret_material_present:false},forbidden_effects_confirmed:[],evidence:['candidate-decision:proof',`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]}
const config={dbPath,issuerId:'synthetic-issuer',actorId:'synthetic-human',credential:token,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'active',pin:APPROVED_PROFILE_PIN},test:{sessionId:'synthetic-one-process-session',waitGuardMs:2000,holdGuardMs:100}}
const verifier=new LocalOwnerVerifier(config);const d=verifier.recordDecision(token,{decisionId:'proof',humanEventRef:'human-proof',baseDecisionRef:'packet-proof',baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,base),requestRef:'request-proof',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z',baseDecision:base});assert(d.ok);verifier.close()
const claim=(id:string,successor:string)=>({decisionId:'proof',decisionDigest:d.value.digest,claimId:id,attemptKey:`attempt-${id}`,successorId:successor,requestRef:'request-proof',action:FIXED_ACTION,claimedAt:'2026-09-05T00:00:01.000Z',expiresAt:'2099-01-01T00:00:00.000Z'})
function child(mode:string,input?:unknown){const proc=fork(path.resolve('scripts/local-owner-proof-child.ts'),[],{execArgv:['--import','tsx'],env:{...process.env,PROOF_CONFIG:JSON.stringify(config),PROOF_TOKEN:token,PROOF_MODE:mode,PROOF_INPUT:JSON.stringify(input??{}),PROOF_DECISION:'proof'},stdio:['ignore','ignore','inherit','ipc']});const messages:any[]=[];proc.on('message',m=>messages.push(m));const wait=(kind:string)=>new Promise<any>((resolve,reject)=>{const check=()=>{const found=messages.find(m=>m.kind===kind);if(found){clearInterval(timer);resolve(found)}};const timer=setInterval(check,5);setTimeout(()=>{clearInterval(timer);reject(Error('timeout'))},10000)});return{proc,wait,messages}}
async function race(mode:string,inputs:unknown[]){const cs=inputs.map(i=>child(mode,i));await Promise.all(cs.map(c=>c.wait('ready')));cs.forEach(c=>c.proc.send('go'));return Promise.all(cs.map(c=>c.wait('result')))}
const claimRace=await race('claim',[claim('claim-a','successor-a'),claim('claim-b','successor-b')]);assert.equal(claimRace.filter(x=>x.result.ok).length,1);assert.equal(claimRace.filter(x=>!x.result.ok&&x.result.stop==='SCOPE_CONFLICT').length,1)
const winner=claimRace.find(x=>x.result.ok)!.result.value;const start={decisionId:'proof',claimId:winner.claimId,intentId:'intent-proof',successorId:winner.successorId,action:FIXED_ACTION}
const startRace=await race('start',[start,start]);assert.equal(startRace.filter(x=>x.result.ok).length,1);assert.equal(startRace.filter(x=>!x.result.ok&&x.result.stop==='HUMAN_DECISION_REQUIRED').length,1)
const reopened=new LocalOwnerVerifier({...config,test:{...config.test,sessionId:'new-session'}});const restart=reopened.guardedStart(token,start);assert(!restart.ok&&restart.stop==='HUMAN_DECISION_REQUIRED');const history=reopened.inspect(token,'proof');reopened.close()
const inventory=JSON.parse(readFileSync('/Users/josephfeser/src/joefeser/hacp-local-continuation-profile/docs/source-packets/wits-v0/local-owner-profile-fixtures.json','utf8')).cases
const sources=['src/local-owner/jcs.ts','src/local-owner/contracts.ts','src/local-owner/verifier.ts','src/local-owner/test.ts','scripts/local-owner-proof.ts','scripts/local-owner-proof-child.ts',...['decision','claim','status-event','start-intent','start-result'].map(k=>`schemas/local-owner/${k}.schema.json`)]
const sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex')
const result={schema:'who-decides.local-owner-proof.v1',observedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),trackedDiffSha256:createHash('sha256').update(execFileSync('git',['diff','HEAD','--'])).digest('hex'),contract:{commit:'664dc73e14d5bd3647e504604b1630e090509100',profileSha256:APPROVED_PROFILE_PIN,fixturesSha256:'6397cce10331d23958b17c67512aae762e7d768547083cac73dfb6f1972e745b'},overlap:{claimRace,startRace},restart,history,inventory:inventory.map((x:any)=>({id:x.id,required:x.expected,coverage:'src/local-owner/test.ts and/or process overlap receipt; full disposition in proof-report.md'})),sourceHashes:Object.fromEntries(sources.map(p=>[p,sha(p)])),secretsExported:false,providerCalls:0,networkCallbacks:0,limitations:['candidate evidence, not owner acceptance','fixed local observation only','no recovery or reexecution','no provider/external effect']};writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:true,inventoryCases:inventory.length,claimRace:startRace.length,startRace:startRace.length,result:path.join(out,'result.json')}))
