import assert from 'node:assert/strict'
import { fork, execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, statfsSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import Database from 'better-sqlite3'
import { LocalOwnerVerifier, APPROVED_PROFILE_PIN } from '../src/local-owner/verifier'
import { FIXED_ACTION } from '../src/local-owner/contracts'
import { PROFILE_ID, PROFILE_VERSION, digestEnvelope, recordDigest } from '../src/local-owner/jcs'
import { deriveProofInventory, EVIDENCE_INTEGRITY_DEFECT, type CaseReceipt } from '../src/local-owner/evidence'
import { bootstrapOwnerAdmittedStore, LOCAL_OWNER_WRITER_VERSION } from '../src/store-admission'
import { LEGACY_CONSUMPTION_WRITER_VERSION } from '../src/store-admission'
import { decisionDigest, type DecisionRecord } from '../src/consumption/store'

const out=path.resolve(process.argv[2]??'');assert(process.argv[2],'output required');mkdirSync(path.dirname(out),{recursive:true});mkdirSync(out)
const receiptPath=path.join(out,'case-receipts.ndjson');writeFileSync(receiptPath,'')
const testOutput=execFileSync('npm',['run','test:local-owner'],{encoding:'utf8',env:{...process.env,LOCAL_OWNER_CASE_RECEIPTS:receiptPath}})
assert.match(testOutput,/owner-admitted store rejects aliases drift unsafe paths and incomplete writer inventory/)
const token='synthetic-proof-credential-000000';const approvedFilesystemTypes=[statfsSync(out,{bigint:true}).type.toString()];const storeAdmission=bootstrapOwnerAdmittedStore({dbPath:path.join(out,'proof.db'),configGeneration:'proof-generation-1',writers:[{role:'local-owner-verifier',version:LOCAL_OWNER_WRITER_VERSION,insertionPath:'LocalOwnerVerifier.recordDecision'}],approvedFilesystemTypes});const dbPath=storeAdmission.canonicalPath
const base={hacp_version:'v0.1-draft',record_kind:'hacp.human_decision_gate',decision_id:'human-proof',packet_id:'packet-proof',profile_id:'hacp-base-draft',profile_version:'v0.1-draft',decision_matrix_version:'0.1',from_status:'approved',to_status:'in_progress',decision:'start_work',reason:'synthetic proof act',created_at:'2026-09-05T00:00:00.000Z',actor_id:'synthetic-human',actor_kind:'human',actor_verification_source:'signed_human_attestation',authentication_context:{interaction_channel:'cli',auth_event_ref:'synthetic-event',secret_material_present:false},forbidden_effects_confirmed:[],evidence:['candidate-decision:proof',`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]}
const restartBase={...base,decision_id:'human-restart-proof',packet_id:'packet-restart-proof',evidence:['candidate-decision:restart-proof',`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]}
const derivedBase=(id:string)=>({...base,decision_id:`human-${id}`,packet_id:`packet-${id}`,evidence:[`candidate-decision:${id}`,`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]})
const concurrentBase=derivedBase('concurrent-proof'),crashBase=derivedBase('crash-proof')
const config={dbPath,storeAdmission,issuerId:'synthetic-issuer',actorId:'synthetic-human',credential:token,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'active',pin:APPROVED_PROFILE_PIN},trustedHumanDecisions:[base,restartBase,concurrentBase,crashBase],test:{waitGuardMs:2000,holdGuardMs:100}}
const verifier=new LocalOwnerVerifier(config);const d=verifier.recordDecision(token,{decisionId:'proof',humanEventRef:'human-proof',baseDecisionRef:'packet-proof',baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,base),requestRef:'request-proof',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z'});assert(d.ok);verifier.close()
const claim=(id:string,successor:string)=>({decisionId:'proof',decisionDigest:d.value.digest,claimId:id,attemptKey:`attempt-${id}`,successorId:successor,requestRef:'request-proof',action:FIXED_ACTION,claimedAt:'2026-09-05T00:00:01.000Z',expiresAt:'2099-01-01T00:00:00.000Z'})
function child(mode:string,input?:unknown,childConfig:any=config,decisionId='proof',revokeReleasePath=''){const proc=fork(path.resolve('scripts/local-owner-proof-child.ts'),[],{execArgv:['--import','tsx'],env:{...process.env,PROOF_CONFIG:JSON.stringify(childConfig),PROOF_TOKEN:token,PROOF_MODE:mode,PROOF_INPUT:JSON.stringify(input??{}),PROOF_DECISION:decisionId,PROOF_REVOKE_RELEASE:revokeReleasePath},stdio:['ignore','ignore','inherit','ipc']});const messages:any[]=[];proc.on('message',m=>messages.push(m));const wait=(kind:string)=>new Promise<any>((resolve,reject)=>{let timeout:any;const timer=setInterval(()=>{const found=messages.find(m=>m.kind===kind);if(found){clearInterval(timer);clearTimeout(timeout);resolve(found)}},5);timeout=setTimeout(()=>{clearInterval(timer);reject(Error('timeout'))},10000)});return{proc,wait,messages}}
const claimChildren=[child('claim',claim('claim-a','successor-a')),child('claim',claim('claim-b','successor-b'))];await Promise.all(claimChildren.map(c=>c.wait('ready')));claimChildren.forEach(c=>c.proc.send('go'));const claimRace=await Promise.all(claimChildren.map(c=>c.wait('result')));assert.equal(claimRace.filter(x=>x.result.ok).length,1);assert.equal(claimRace.filter(x=>!x.result.ok&&x.result.stop==='SCOPE_CONFLICT').length,1)
const winner=claimRace.find(x=>x.result.ok)!,winnerChild=claimChildren.find(c=>c.messages.some(m=>m.pid===winner.pid))!,winnerClaim=winner.result.value;const start={decisionId:'proof',claimId:winnerClaim.claimId,intentId:'intent-proof',successorId:winnerClaim.successorId,action:FIXED_ACTION}
const contender=child('start',start);await contender.wait('ready');winnerChild.proc.send(start);contender.proc.send('go');const startRace=await Promise.all([winnerChild.wait('startResult'),contender.wait('result')]);assert.equal(startRace.filter(x=>x.result.ok).length,1);assert.equal(startRace.filter(x=>!x.result.ok&&x.result.stop==='HUMAN_DECISION_REQUIRED').length,1)
const restartVerifier=new LocalOwnerVerifier(config);const rd=restartVerifier.recordDecision(token,{decisionId:'restart-proof',humanEventRef:'human-restart-proof',baseDecisionRef:'packet-restart-proof',baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,restartBase),requestRef:'request-restart',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z'});assert(rd.ok);const rc=restartVerifier.admitClaim(token,{...claim('restart-claim','restart-successor'),decisionId:'restart-proof',decisionDigest:rd.value.digest,requestRef:'request-restart'});assert(rc.ok);restartVerifier.close();const restartStart={decisionId:'restart-proof',claimId:'restart-claim',intentId:'restart-intent',successorId:'restart-successor',action:FIXED_ACTION};const restartChild=child('start',restartStart);await restartChild.wait('ready');restartChild.proc.send('go');const restart=(await restartChild.wait('result')).result;assert(!restart.ok&&restart.stop==='HUMAN_DECISION_REQUIRED');const reopened=new LocalOwnerVerifier(config);const history=reopened.inspect(token,'proof');reopened.close()
const decisionFor=(id:string,human:any,requestRef:string)=>({decisionId:id,humanEventRef:human.decision_id,baseDecisionRef:human.packet_id,baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,human),requestRef,action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z'})
const prepare=new LocalOwnerVerifier(config);const concurrentDecision=prepare.recordDecision(token,decisionFor('concurrent-proof',concurrentBase,'request-concurrent'));assert(concurrentDecision.ok);prepare.close()
const concurrentClaim={...claim('concurrent-claim','concurrent-successor'),decisionId:'concurrent-proof',decisionDigest:concurrentDecision.value.digest,requestRef:'request-concurrent'};const claimant=child('claim',concurrentClaim);await claimant.wait('ready');claimant.proc.send('go');const claimantResult=await claimant.wait('result');assert(claimantResult.result.ok)
const concurrentStart={decisionId:'concurrent-proof',claimId:'concurrent-claim',intentId:'concurrent-intent',successorId:'concurrent-successor',action:FIXED_ACTION};const revokeReleasePath=path.join(out,'revoke-release');const revoker=child('revoke',undefined,config,'concurrent-proof',revokeReleasePath);await revoker.wait('ready');revoker.proc.send('go');const revokeBegan=await revoker.wait('began');const revokeGuardHeld=await revoker.wait('revokeGuardHeld');claimant.proc.send(concurrentStart);const startBegan=await claimant.wait('startBegan');writeFileSync(revokeReleasePath,'release');const [revokeResult,concurrentStartResult]=await Promise.all([revoker.wait('result'),claimant.wait('startResult')]);assert(revokeResult.result.ok);assert(!concurrentStartResult.result.ok&&concurrentStartResult.result.stop==='STALE_PACKET');assert(BigInt(revokeGuardHeld.monotonicNanoseconds)<BigInt(startBegan.monotonicNanoseconds)&&BigInt(startBegan.monotonicNanoseconds)<BigInt(revokeResult.monotonicNanoseconds));const concurrencyDb=new Database(dbPath,{readonly:true});const concurrentSlot=concurrencyDb.prepare('select decision_digest,decision_status_head,start_intent_digest from local_owner_slots where issuer_id=? and decision_id=?').get(config.issuerId,'concurrent-proof') as any;const concurrentStatuses=(concurrencyDb.prepare("select sequence,digest,record_json from local_owner_status where issuer_id=? and decision_id=? and target_kind='decision' order by sequence").all(config.issuerId,'concurrent-proof') as any[]).map(row=>({...row,record:JSON.parse(row.record_json)}));const concurrentWork=(concurrencyDb.prepare("select count(*) n from local_owner_records where issuer_id=? and decision_id=? and kind in ('start-intent','start-result')").get(config.issuerId,'concurrent-proof') as any).n;concurrencyDb.close();assert.equal(concurrentWork,0);assert.equal(concurrentSlot.start_intent_digest,null);assert.deepEqual(concurrentStatuses.map(row=>row.sequence),[0,1]);assert.equal(concurrentStatuses[0].record.state,'active');assert.equal(concurrentStatuses[1].record.state,'revoked');assert.equal(concurrentStatuses[1].record.previousDigest,concurrentStatuses[0].digest);assert.equal(concurrentStatuses[1].record.targetDigest,concurrentSlot.decision_digest);assert.equal(concurrentStatuses[1].digest,concurrentSlot.decision_status_head);const concurrentEvidence={revokeResult,concurrentStartResult,revokeBegan,revokeGuardHeld,startBegan,concurrentSlot,concurrentStatuses,concurrentWork}
const crashPrepare=new LocalOwnerVerifier(config);const crashDecision=crashPrepare.recordDecision(token,decisionFor('crash-proof',crashBase,'request-crash'));assert(crashDecision.ok);crashPrepare.close();const crashConfig={...config,test:{...config.test,crashAfterIntent:true}};const crashClaim={...claim('crash-claim','crash-successor'),decisionId:'crash-proof',decisionDigest:crashDecision.value.digest,requestRef:'request-crash'};const crasher=child('claim',crashClaim,crashConfig);await crasher.wait('ready');crasher.proc.send('go');assert((await crasher.wait('result')).result.ok);const crashStart={decisionId:'crash-proof',claimId:'crash-claim',intentId:'crash-intent',successorId:'crash-successor',action:FIXED_ACTION};const crashExit=new Promise<number|null>(resolve=>crasher.proc.once('exit',resolve));crasher.proc.send(crashStart);assert.equal(await crashExit,91);const afterCrash=new LocalOwnerVerifier(config);const crashHistory=afterCrash.inspect(token,'crash-proof');assert(crashHistory.ok&&crashHistory.value.start_intent_digest);const crashRestart=afterCrash.guardedStart(token,crashStart);assert(!crashRestart.ok&&crashRestart.stop==='HUMAN_DECISION_REQUIRED');afterCrash.close()

const candidateWriter={role:'local-owner-verifier',version:LOCAL_OWNER_WRITER_VERSION,insertionPath:'LocalOwnerVerifier.recordDecision'}
const legacyWriter={role:'legacy-consumption-writer',version:LEGACY_CONSUMPTION_WRITER_VERSION,insertionPath:'ConsumptionStore.claim'}
function raceChild(mode:'legacy'|'candidate',raceConfig:any,releasePath='') { const proc=fork(path.resolve('scripts/local-owner-legacy-race-child.ts'),[],{execArgv:['--import','tsx'],env:{...process.env,PROOF_RACE_MODE:mode,PROOF_RACE_CONFIG:JSON.stringify(raceConfig),PROOF_RACE_RELEASE:releasePath,PROOF_RACE_TOKEN:token},stdio:['ignore','ignore','inherit','ipc']});const messages:any[]=[];proc.on('message',message=>messages.push(message));const wait=(kind:string)=>new Promise<any>((resolve,reject)=>{let timeout:any;const timer=setInterval(()=>{const found=messages.find(message=>message.kind===kind);if(found){clearInterval(timer);clearTimeout(timeout);resolve(found)}},5);timeout=setTimeout(()=>{clearInterval(timer);reject(Error(`race child timeout: ${mode} ${kind}`))},10000)});const exited=new Promise<number|null>(resolve=>proc.once('exit',resolve));return{proc,wait,exited,messages} }
async function runLegacyCandidateRace(order:'legacy-first'|'candidate-first') {
  const raceDir=path.join(out,order);mkdirSync(raceDir)
  const raceAdmission=bootstrapOwnerAdmittedStore({dbPath:path.join(raceDir,'shared.db'),configGeneration:`proof-${order}-generation-1`,writers:[candidateWriter,legacyWriter],approvedFilesystemTypes})
  const raceId=`race-${order}`;const raceBase=derivedBase(raceId)
  const candidateConfig={dbPath:raceAdmission.canonicalPath,storeAdmission:raceAdmission,issuerId:'synthetic-issuer',actorId:'synthetic-human',credential:token,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'active',pin:APPROVED_PROFILE_PIN},trustedHumanDecisions:[raceBase]}
  const legacyConfig={dbPath:raceAdmission.canonicalPath,storeAdmission:raceAdmission,writer:legacyWriter}
  const releasePath=path.join(raceDir,'release')
  const first=order==='legacy-first'?raceChild('legacy',legacyConfig,releasePath):raceChild('candidate',candidateConfig,releasePath);await first.wait('ready')
  const second=order==='legacy-first'?raceChild('candidate',candidateConfig):raceChild('legacy',legacyConfig);await second.wait('ready')
  const legacy=order==='legacy-first'?first:second;const candidate=order==='candidate-first'?first:second
  const legacyDecision:DecisionRecord={decisionId:raceId,chosenOption:'start_work',rationale:'synthetic legacy collision',decidedAt:'2026-09-05T00:00:00.000Z',decisionRequestId:`legacy-request-${order}`,permittedAction:'legacy dry-run claim',expiresAt:'2100-01-01T00:00:00.000Z'}
  const candidateInput=decisionFor(raceId,raceBase,`candidate-request-${order}`)
  const winner=order==='legacy-first'?legacy:candidate;const loser=order==='legacy-first'?candidate:legacy
  winner.proc.send(order==='legacy-first'?{decision:legacyDecision,successor:`legacy-successor-${order}`}:candidateInput)
  const lockHeld=await winner.wait('writeLockHeld')
  loser.proc.send(order==='legacy-first'?candidateInput:{decision:legacyDecision,successor:`legacy-successor-${order}`})
  const loserBeforeBegin=await loser.wait('beforeBeginImmediate')
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,75)
  const loserBlockedBeforeRelease=!loser.messages.some(message=>message.kind==='result');assert(loserBlockedBeforeRelease)
  const releaseMonotonicNanoseconds=process.hrtime.bigint().toString();assert(BigInt(lockHeld.monotonicNanoseconds)<BigInt(loserBeforeBegin.monotonicNanoseconds)&&BigInt(loserBeforeBegin.monotonicNanoseconds)<BigInt(releaseMonotonicNanoseconds))
  writeFileSync(releasePath,'release')
  const [legacyResult,candidateResult]=await Promise.all([legacy.wait('result'),candidate.wait('result')])
  assert.equal(await legacy.exited,0);assert.equal(await candidate.exited,0)
  if(order==='legacy-first'){assert.equal(legacyResult.result.status,'claimed');assert.deepEqual(candidateResult.result,{ok:false,stop:'MISSING_AUTHORITY',detail:'legacy decision-id collision'})}
  else{assert.equal(candidateResult.result.ok,true);assert.equal(legacyResult.result.status,'rejected');assert.equal(legacyResult.result.reason,'profile_slot_conflict')}
  const reopened=new Database(raceAdmission.canonicalPath,{readonly:true,fileMustExist:true})
  const receipts=reopened.prepare('SELECT decision_id,receipt_json,decision_digest FROM consumption_receipts WHERE decision_id=?').all(raceId) as Array<{decision_id:string,receipt_json:string,decision_digest:string}>
  const slots=reopened.prepare('SELECT issuer_id,decision_id,decision_digest FROM local_owner_slots WHERE decision_id=?').all(raceId) as Array<{issuer_id:string,decision_id:string,decision_digest:string}>
  const records=reopened.prepare("SELECT kind,digest,record_json FROM local_owner_records WHERE decision_id=? AND kind='decision'").all(raceId) as Array<{kind:string,digest:string,record_json:string}>
  const integrity=String(reopened.pragma('integrity_check',{simple:true}));reopened.close()
  assert.equal(receipts.length+slots.length,1);assert.equal(integrity,'ok')
  if(order==='legacy-first'){assert.equal(receipts.length,1);assert.equal(slots.length,0);assert.equal(records.length,0);assert.equal(receipts[0].decision_digest,decisionDigest(legacyDecision));assert.equal(JSON.parse(receipts[0].receipt_json).decisionId,raceId)}
  else{assert.equal(slots.length,1);assert.equal(receipts.length,0);assert.equal(records.length,1);const record=JSON.parse(records[0].record_json);assert.equal(record.digest.value,records[0].digest);assert.equal(recordDigest('decision',record).value,records[0].digest)}
  return{order,databaseIdentity:{databaseId:raceAdmission.databaseId,canonicalPath:raceAdmission.canonicalPath,device:raceAdmission.device,inode:raceAdmission.inode,filesystemType:raceAdmission.filesystemType,schemaSha256:raceAdmission.schemaSha256,configGeneration:raceAdmission.configGeneration},processes:{legacyPid:legacyResult.pid,candidatePid:candidateResult.pid,separate:legacyResult.pid!==candidateResult.pid},overlap:{lockHeld,loserBeforeBegin,loserBlockedBeforeRelease,releaseMonotonicNanoseconds},results:{legacy:legacyResult,candidate:candidateResult},durableReadback:{receiptCount:receipts.length,slotCount:slots.length,unionCount:receipts.length+slots.length,legacyReceiptBytesSha256:receipts[0]?createHash('sha256').update(receipts[0].receipt_json).digest('hex'):null,legacyDecisionDigest:receipts[0]?.decision_digest??null,candidateRecordBytesSha256:records[0]?createHash('sha256').update(records[0].record_json).digest('hex'):null,candidateDecisionDigest:records[0]?.digest??null,integrity}}
}
const legacyFirst=await runLegacyCandidateRace('legacy-first');const candidateFirst=await runLegacyCandidateRace('candidate-first')
const inventory=JSON.parse(readFileSync('docs/contracts/local-owner-continuation/local-owner-profile-fixtures.json','utf8')).cases
const sources=['docs/contracts/local-owner-continuation/local-owner-profile.md','docs/contracts/local-owner-continuation/local-owner-profile-fixtures.json','docs/contracts/local-owner-continuation/local-owner-profile-review-synthesis.md','src/store-admission.ts','src/store-schema.ts','src/consumption/store.ts','src/local-owner/jcs.ts','src/local-owner/contracts.ts','src/local-owner/evidence.ts','src/local-owner/verifier.ts','src/local-owner/test.ts','scripts/local-owner-proof.ts','scripts/local-owner-proof-child.ts','scripts/local-owner-legacy-race-child.ts',...['decision','claim','status-event','start-intent','start-result'].map(k=>`schemas/local-owner/${k}.schema.json`)]
const sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex')
const unitReceipts=readFileSync(receiptPath,'utf8').trim().split('\n').filter(Boolean).map(line=>JSON.parse(line) as CaseReceipt);const processReceipts:CaseReceipt[]=[{id:'two-overlapping-claims',test:'two child-process claims',status:'passed',evidence:claimRace},{id:'two-overlapping-starts',test:'claimant and restarted child-process starts',status:'passed',evidence:startRace},{id:'restart-after-claim-before-intent',test:'fresh process after claim',status:'passed',evidence:restart},{id:'concurrent-revoke-start',test:'overlapping revoke before claimant start',status:'passed',evidence:concurrentEvidence},{id:'revocation-before-handoff',test:'overlapping revoke before claimant start with durable status-chain readback',status:'passed',evidence:concurrentEvidence},{id:'crash-after-intent-before-result',test:'claimant process exits after durable intent',status:'passed',evidence:{exitCode:91,crashHistory,crashRestart}},{id:'legacy-insert-races-profile-admission',test:'same admitted SQLite main database, both real lock-winner orderings and negative startup matrix',status:'passed',evidence:{legacyFirst,candidateFirst,negativeStartupTest:'owner-admitted store rejects aliases drift unsafe paths and incomplete writer inventory',negativeStartupTestOutputSha256:createHash('sha256').update(testOutput).digest('hex')}}];const proofInventory=deriveProofInventory(inventory,[...unitReceipts,...processReceipts]);const uncovered=proofInventory.filter(x=>x.status==='uncovered').map(x=>x.id);assert.deepEqual(uncovered,[])
const result={schema:'who-decides.local-owner-proof.v3',observedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),trackedDiffSha256:createHash('sha256').update(execFileSync('git',['diff','HEAD','--'])).digest('hex'),contract:{commit:'3b61e64d61984f0c5617c4a71266802f31961494',profileSha256:APPROVED_PROFILE_PIN,fixturesSha256:'463f25a09db48863d03344a5225576052d944622d04c997d65057c89c2e77aa0',synthesisSha256:'4995b0e2603d695cd005c2bcbfb8e6a6ada1664ff079b148fc20f8b105ba8805'},evidenceIntegrity:{defectSpecies:EVIDENCE_INTEGRITY_DEFECT,rule:'an inventory case is observed iff a passing unit or process receipt with the exact fixture id exists'},testRun:{command:'npm run test:local-owner',passed:true,outputSha256:createHash('sha256').update(testOutput).digest('hex'),receiptCount:unitReceipts.length},overlap:{claimRace,startRace,concurrentRevokeStart:{revokeResult,concurrentStartResult},legacyCandidate:{legacyFirst,candidateFirst}},restart,crash:{crashHistory,crashRestart},history,inventory:proofInventory,sourceHashes:Object.fromEntries(sources.map(p=>[p,sha(p)])),secretsExported:false,providerCalls:0,networkCallbacks:0,limitations:['candidate evidence, not owner acceptance','same-file-only closed-world support; separate stores, unlisted/direct writers, unsupported locking filesystems and distributed trust remain unsupported','fixed local observation only','no migration, recovery or reexecution','no provider/external effect']};writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:true,inventoryCases:inventory.length,observedCases:proofInventory.length-uncovered.length,uncoveredCases:uncovered.length,uncovered,unitReceipts:unitReceipts.length,processReceipts:processReceipts.length,result:path.join(out,'result.json')}))
