import assert from 'node:assert/strict'
import { fork, execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { LocalOwnerVerifier, APPROVED_PROFILE_PIN } from '../src/local-owner/verifier'
import { FIXED_ACTION } from '../src/local-owner/contracts'
import { PROFILE_ID, PROFILE_VERSION, digestEnvelope, recordDigest } from '../src/local-owner/jcs'

const out=path.resolve(process.argv[2]??'');assert(process.argv[2],'output required');mkdirSync(path.dirname(out),{recursive:true});mkdirSync(out)
const testOutput=execFileSync('npm',['run','test:local-owner'],{encoding:'utf8'})
const token='synthetic-proof-credential-000000';const dbPath=path.join(out,'proof.db')
const base={hacp_version:'v0.1-draft',record_kind:'hacp.human_decision_gate',decision_id:'human-proof',packet_id:'packet-proof',profile_id:'hacp-base-draft',profile_version:'v0.1-draft',decision_matrix_version:'0.1',from_status:'approved',to_status:'in_progress',decision:'start_work',reason:'synthetic proof act',created_at:'2026-09-05T00:00:00.000Z',actor_id:'synthetic-human',actor_kind:'human',actor_verification_source:'signed_human_attestation',authentication_context:{interaction_channel:'cli',auth_event_ref:'synthetic-event',secret_material_present:false},forbidden_effects_confirmed:[],evidence:['candidate-decision:proof',`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]}
const restartBase={...base,decision_id:'human-restart-proof',packet_id:'packet-restart-proof',evidence:['candidate-decision:restart-proof',`candidate-action:${recordDigest('action',FIXED_ACTION as any).value}`]}
const config={dbPath,issuerId:'synthetic-issuer',actorId:'synthetic-human',credential:token,selectedProfile:{id:PROFILE_ID,version:PROFILE_VERSION,status:'active',pin:APPROVED_PROFILE_PIN},trustedHumanDecisions:[base,restartBase],test:{waitGuardMs:2000,holdGuardMs:100}}
const verifier=new LocalOwnerVerifier(config);const d=verifier.recordDecision(token,{decisionId:'proof',humanEventRef:'human-proof',baseDecisionRef:'packet-proof',baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,base),requestRef:'request-proof',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z'});assert(d.ok);verifier.close()
const claim=(id:string,successor:string)=>({decisionId:'proof',decisionDigest:d.value.digest,claimId:id,attemptKey:`attempt-${id}`,successorId:successor,requestRef:'request-proof',action:FIXED_ACTION,claimedAt:'2026-09-05T00:00:01.000Z',expiresAt:'2099-01-01T00:00:00.000Z'})
function child(mode:string,input?:unknown){const proc=fork(path.resolve('scripts/local-owner-proof-child.ts'),[],{execArgv:['--import','tsx'],env:{...process.env,PROOF_CONFIG:JSON.stringify(config),PROOF_TOKEN:token,PROOF_MODE:mode,PROOF_INPUT:JSON.stringify(input??{}),PROOF_DECISION:'proof'},stdio:['ignore','ignore','inherit','ipc']});const messages:any[]=[];proc.on('message',m=>messages.push(m));const wait=(kind:string)=>new Promise<any>((resolve,reject)=>{let timeout:any;const timer=setInterval(()=>{const found=messages.find(m=>m.kind===kind);if(found){clearInterval(timer);clearTimeout(timeout);resolve(found)}},5);timeout=setTimeout(()=>{clearInterval(timer);reject(Error('timeout'))},10000)});return{proc,wait,messages}}
const claimChildren=[child('claim',claim('claim-a','successor-a')),child('claim',claim('claim-b','successor-b'))];await Promise.all(claimChildren.map(c=>c.wait('ready')));claimChildren.forEach(c=>c.proc.send('go'));const claimRace=await Promise.all(claimChildren.map(c=>c.wait('result')));assert.equal(claimRace.filter(x=>x.result.ok).length,1);assert.equal(claimRace.filter(x=>!x.result.ok&&x.result.stop==='SCOPE_CONFLICT').length,1)
const winner=claimRace.find(x=>x.result.ok)!,winnerChild=claimChildren.find(c=>c.messages.some(m=>m.pid===winner.pid))!,winnerClaim=winner.result.value;const start={decisionId:'proof',claimId:winnerClaim.claimId,intentId:'intent-proof',successorId:winnerClaim.successorId,action:FIXED_ACTION}
const contender=child('start',start);await contender.wait('ready');winnerChild.proc.send(start);contender.proc.send('go');const startRace=await Promise.all([winnerChild.wait('startResult'),contender.wait('result')]);assert.equal(startRace.filter(x=>x.result.ok).length,1);assert.equal(startRace.filter(x=>!x.result.ok&&x.result.stop==='HUMAN_DECISION_REQUIRED').length,1)
const restartVerifier=new LocalOwnerVerifier(config);const rd=restartVerifier.recordDecision(token,{decisionId:'restart-proof',humanEventRef:'human-restart-proof',baseDecisionRef:'packet-restart-proof',baseDecisionDigest:digestEnvelope(`${PROFILE_ID}.base-decision-reference.0.1-candidate`,restartBase),requestRef:'request-restart',action:FIXED_ACTION,approvedAt:'2026-09-05T00:00:00.000Z',expiresAt:'2100-01-01T00:00:00.000Z'});assert(rd.ok);const rc=restartVerifier.admitClaim(token,{...claim('restart-claim','restart-successor'),decisionId:'restart-proof',decisionDigest:rd.value.digest,requestRef:'request-restart'});assert(rc.ok);restartVerifier.close();const restartStart={decisionId:'restart-proof',claimId:'restart-claim',intentId:'restart-intent',successorId:'restart-successor',action:FIXED_ACTION};const restartChild=child('start',restartStart);await restartChild.wait('ready');restartChild.proc.send('go');const restart=(await restartChild.wait('result')).result;assert(!restart.ok&&restart.stop==='HUMAN_DECISION_REQUIRED');const reopened=new LocalOwnerVerifier(config);const history=reopened.inspect(token,'proof');reopened.close()
const inventory=JSON.parse(readFileSync('docs/contracts/local-owner-continuation/local-owner-profile-fixtures.json','utf8')).cases
const sources=['docs/contracts/local-owner-continuation/local-owner-profile.md','docs/contracts/local-owner-continuation/local-owner-profile-fixtures.json','docs/contracts/local-owner-continuation/local-owner-profile-review-synthesis.md','src/local-owner/jcs.ts','src/local-owner/contracts.ts','src/local-owner/verifier.ts','src/local-owner/test.ts','scripts/local-owner-proof.ts','scripts/local-owner-proof-child.ts',...['decision','claim','status-event','start-intent','start-result'].map(k=>`schemas/local-owner/${k}.schema.json`)]
const sha=(p:string)=>createHash('sha256').update(readFileSync(p)).digest('hex')
const processCases=new Set(['two-overlapping-claims','two-overlapping-starts','restart-after-claim-before-intent'])
const unitCases=new Set(['authenticated-happy-path','missing-or-wrong-authentication','authenticated-without-human-act','unrelated-or-reused-human-act','two-overlapping-claims','same-id-different-issuer','changed-binding-replay','exact-claim-retry','legacy-id-collision','unknown-profile-or-stripped-context','unsupported-action-or-parameter','missing-or-corrupt-durable-readback','absent-or-corrupt-status','claim-revoked-decision-active','expiry-between-intent-and-handoff','two-overlapping-starts','clock-rollback-or-unknown-time','wall-clock-stall-crosses-monotonic-deadline','restart-after-claim-before-intent','completed-start-replay','revoked-status-reset','digest-known-answer-and-domain-mismatch','profile-declaration-status','clock-sample-shape','observation-digest-completed-or-uncertain','base-decision-companion-digest','closed-base-record-remains-unchanged'])
const result={schema:'who-decides.local-owner-proof.v1',observedAt:new Date().toISOString(),gitHead:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),trackedDiffSha256:createHash('sha256').update(execFileSync('git',['diff','HEAD','--'])).digest('hex'),contract:{commit:'3b61e64d61984f0c5617c4a71266802f31961494',profileSha256:APPROVED_PROFILE_PIN,fixturesSha256:'463f25a09db48863d03344a5225576052d944622d04c997d65057c89c2e77aa0',synthesisSha256:'4995b0e2603d695cd005c2bcbfb8e6a6ada1664ff079b148fc20f8b105ba8805'},testRun:{command:'npm run test:local-owner',passed:true,outputSha256:createHash('sha256').update(testOutput).digest('hex')},overlap:{claimRace,startRace},restart,history,inventory:inventory.map((x:any)=>({id:x.id,required:x.expected,status:processCases.has(x.id)?'observed-process':unitCases.has(x.id)?'observed-unit':'uncovered',evidence:processCases.has(x.id)?'actual child-process result embedded in this receipt':unitCases.has(x.id)?'passing test run embedded by hash and case exercised in src/local-owner/test.ts':'inventory retained without a claim of execution'})),sourceHashes:Object.fromEntries(sources.map(p=>[p,sha(p)])),secretsExported:false,providerCalls:0,networkCallbacks:0,limitations:['candidate evidence, not owner acceptance','inventory entries marked uncovered are not claimed as observed','fixed local observation only','no recovery or reexecution','no provider/external effect']};writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({passed:true,inventoryCases:inventory.length,observedCases:result.inventory.filter((x:any)=>x.status!=='uncovered').length,uncoveredCases:result.inventory.filter((x:any)=>x.status==='uncovered').length,claimRace:claimRace.length,startRace:startRace.length,result:path.join(out,'result.json')}))
